<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie ie9" lang="en" class="no-js"> <![endif]-->
<!--[if !(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
	<title>FUERZA DE VENTAS A365</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="FFVV BUZON A465">
	<meta name="author" content="ACOA">

	<!-- CSS -->
	<link href="<?php echo BASE_URL ?>public/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo BASE_URL ?>public/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo BASE_URL ?>public/assets/css/main.css" rel="stylesheet" type="text/css">

	<!-- Javascript -->
	<script src="<?php echo BASE_URL ?>public/assets/js/jquery/jquery-3.0.0.js"></script>
	<script src="<?php echo BASE_URL ?>public/assets/js/bootstrap/bootstrap.min.js"></script>
    <script src="<?php echo BASE_URL ?>public/assets/js/plugins/modernizr/modernizr.js"></script>

	<!-- Fav and touch icons -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo BASE_URL ?>public/assets/ico/kingadmin-favicon144x144.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo BASE_URL ?>public/assets/ico/kingadmin-favicon114x114.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo BASE_URL ?>public/assets/ico/kingadmin-favicon72x72.png">
	<link rel="apple-touch-icon-precomposed" sizes="57x57" href="<?php echo BASE_URL ?>public/assets/ico/kingadmin-favicon57x57.png">
	<!-- <link rel="shortcut icon" href="<?php echo BASE_URL ?>public/assets/ico/favicon.png"> -->

		<?php if(isset($_layoutParams['js']) && count($_layoutParams['js'])): ?>
		<?php foreach($_layoutParams['js'] as $layout): ?>
   			<script src="<?php echo  $layout ?>" type="text/javascript"></script>
		<?php endforeach; ?>
	<?php endif; ?>

</head>

<body>
	<div class="wrapper full-page-wrapper page-auth page-login text-center">
		<div class="inner-page">
		<div class="form-group">
			<div class="logo">
				<a><img height="110px" width="200px" src="<?php echo BASE_URL ?>public/assets/img/logo.png" alt="A365" title="A365" /></a>
				<a><img height="110px" width="120px" src="<?php echo BASE_URL ?>public/assets/img/claro.png" alt="CLARO" title="CLARO" /></a>
			</div>
		</div>
			<div class="login-box center-block">
				<form class="form-horizontal" role="form"  action="" method='post'>
					<p class="title"><?php echo ('Control de acceso')?></p>
					<div class="form-group">
						<label for="username" class="control-label sr-only"><?php echo ('usuario')?></label>
						<div class="col-sm-12">
							<div class="input-group">
								<input type="text" placeholder="<?php echo ('usuario')?>" id="user" class="form-control">
								<span class="input-group-addon"><i class="fa fa-user"></i></span>
							</div>
						</div>
					</div>
					<label for="password" class="control-label sr-only"><?php echo ('Contraseña')?></label>
					<div class="form-group">
						<div class="col-sm-12">
							<div class="input-group">
								<input type="password" placeholder="<?php echo ('Contraseña')?>" id="pass" class="form-control">
								<span class="input-group-addon"><i class="fa fa-lock"></i></span>
							</div>
						</div>
					</div>
					<div class="alert alert-danger alert-dismissable" style="display: none;" id="mensajes" name="mensajes">
					  <span id='mensaje'> </span>
					</div>

					<label class="fancy-checkbox">
						<input type="checkbox">
						<span><?php echo ('Recordar contraseña')?></span>
					</label>
					<button type='button' class="btn btn-danger btn-lg btn-block btn-auth" id='btn_ingresar'><i class="fa fa-arrow-circle-o-right"></i> <?php echo ('Ingresar')?></button>
				</form>

				<div class="links">
					<p><a href="#"><?php echo ('¿Olvido su password?')?></a></p>

				</div>
			</div>
		</div>
	</div>

	<footer class="footer">&copy;  Copyright <?php echo date('Y');?> AAPCOA. All rights reserved.</footer>


</body>



</html>
