
<div class="wrapper page-error text-center">
		<div class="inner-page">
			<h1>
				<span class="clearfix title">
					<span class="number">404</span> <span class="text">Ups! <br/>Pagina no encontrada</span>
				</span>
			</h1>

			<p>La pagina a la que intentas acceder no se encuentra.</p>
			<p>Por favor verifica que la ruta este correctamente escrita o tengas los permisos correspondientes.</p>
		</div>
</div>
	
</div>
<!-- /main -->
</div>
<!-- /content-wrapper -->
</div>
<!-- /row -->
</div>
<!-- /container -->
</div>
<!-- END BOTTOM: LEFT NAV AND RIGHT MAIN CONTENT -->
</div>
<!-- /wrapper -->