<!-- main -->
<div class="content">
	<div class="main-content">

		<input style="display: none;" name="tipo_usuario" id="tipo_usuario" value="<?php echo $tipo_usuario;?>">
		<input style="display: none;" name="usuario_rea" id="usuario_rea" value="<?php echo $_SESSION['user'];?>">
		<input style="display: none;" name="ip_rea" id="ip_rea" value="<?php echo $_SERVER['REMOTE_ADDR'];?>">

<!-- Aqui va el contenido -->

<!-- main -->
<div class="content">
	<!-- main-content -->
	<div class="main-content">
		<!-- <legend>Registro Agencia</legend> -->
		<form method="post" id="formulario" name="formulario">

	<!-- DATOS DE USUARIO -->
				<p><strong>DATOS DE USUARIO</strong></p>
				<legend></legend>
				<br>

				<div class="row">

					<div class="form-group col-sm-6">
						<label class="col-md-3 control-label">Tipo Doc</label>
						<div class="col-md-8">
							<select class="form-control input-sm" name="tipo_documento" id="tipo_documento">
								<option value="">SELECCIONE</option>
								<?php foreach($this->tipo_documento  as $indice =>$value):?>
								<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
								<?php  endforeach;?>
							</select>
						</div>
					</div>

					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Nro Doc</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="documento"
								name="documento" placeholder="Nro de Documento*">
						</div>
					</div>

				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="ticket-nombres" class="col-sm-3 control-label">Nombres</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="nombres"
								name="nombres" placeholder="Nombres">
						</div>
					</div>

					<div class="form-group col-sm-6">
						<label for="ticket-paterno" class="col-sm-3 control-label">Apellidos</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="apellidos"
								name="apellidos" placeholder="Apellidos">
						</div>
					</div>
				</div>

				<div class="row">

					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Telefono 1</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="telefono1"
								name="telefono1" placeholder="Telefono 1">
						</div>
					</div>

					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Telefono 2</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="telefono2"
								name="telefono2" placeholder="Telefono 2">
						</div>
					</div>

				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Dirección</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="direccion"
								name="direccion" placeholder="Dirección">
						</div>
					</div>

					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Email</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="email"
								name="email" placeholder="Email">
						</div>
					</div>
				</div>

			<br>
		<!-- CREACION DE USUARIO -->

			<div class="widget-content">
				<p><strong>CREACION DE USUARIO</strong></p>
				<legend></legend>
				<br>
				<div class="row">
					<div class="form-group col-sm-6">
						<label class="col-md-3 control-label">Tipo Usuario</label>
						<div class="col-md-8">
							<select class="form-control input-sm" name="tipo_usuarios" id="tipo_usuarios">
								<option value="">SELECCIONE</option>
								<?php foreach($this->tipo_usuario as $indice =>$value):?>
								<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
								<?php  endforeach;?>
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Usuario</label>
						<div class="col-sm-8">
							<input type="text" class="form-control input-sm" id="usuario"
								name="usuario" placeholder="Nombre Usuario*">
						</div>
					</div>

					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Password</label>
						<div class="col-sm-8">
							<input type="password" class="form-control input-sm" id="password"
								name="password" placeholder="Password*">
						</div>
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="ticket-nro" class="col-sm-3 control-label">Accesos</label>
						<div class="col-sm-8">
							<select multiple id="grupo" name="grupo[]" class="select2 select2-multiple">
								<?php foreach($this->tipo_acceso as $indice =>$value):?>
								<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
								<?php  endforeach;?>
							</select>
						</div>
					</div>
				</div>


					<br>
					<div class="row">
						<div class="form-group col-sm-6">
							<div class="col-sm-8 col-sm-offset-11" id="oculto_boton"
								name="oculto_boton">
								<button type="button" class="btn btn-default" id="btn_Grabar">
									<i class="fa fa-floppy-o"></i> Grabar
								</button>
							</div>
						</div>
					</div>

				</div>
		</div>
		<!-- FIN CREACION DE USUARIO -->
		</form>
	</div>
	<!-- /main-content -->
</div>
<!-- /main -->
</div>
<!-- /content-wrapper -->
</div>
<!-- /row -->
</div>
<!-- /container -->
</div>
<!-- END BOTTOM: LEFT NAV AND RIGHT MAIN CONTENT -->
</div>
<!-- /wrapper -->

<! -- Hasta aqui va el contenido -->

	</div>
	<!-- /main-content -->
</div>
<!-- /main -->
</div>
<!-- /content-wrapper -->
</div>
<!-- /row -->
</div>
<!-- /container -->
</div>
<!-- END BOTTOM: LEFT NAV AND RIGHT MAIN CONTENT -->
</div>
<!-- /wrapper -->
