<!-- main -->
<div class="content">
	<div class="main-content">	
		<div class="row">
			<form class="form-horizontal" role="form" method="post" name="principal" id="principal" enctype="multipart/form-data" >
				<div class="row">
					<div class="form-group col-sm-12">
						<label class="col-md-2 col-md-offset-2 control-label"><strong>TIPO OPERACI&Oacute;N</strong></label>
						<div class="col-md-4">
							<select class="form-control" name="tipo_operacion"
								id="tipo_operacion">
								<option>SELECCIONE</option>
										<?php foreach($this->tipo_operacion  as $indice =>$value):?>						
										<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
										<?php  endforeach;?>
							</select>
						</div>
					</div>
				</div>
				
				<!-- NUEVA EVALUACION -->
				<div class="widget">
					<div class="widget-header">
						<h3>
							<i class="fa fa-plus"></i> Nueva Evaluaci&oacute;n
						</h3>
					</div>
					<div class="widget-content">						
						<div class="row">
						
								<div class="form-group col-sm-4">
									<label class="col-md-3 control-label">Tipo Doc</label>
									<div class="col-md-9">
										<select class="form-control input-sm" name="tipo_documento" id="tipo_documento">
											<option value="">SELECCIONE</option>
											<?php foreach($this->tipo_documento  as $indice =>$value):?>						
											<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
											<?php  endforeach;?>
										</select>
									</div>	
								</div>
								
								<div class="form-group col-sm-4">
									<label for="ticket-nro" class="col-sm-4 control-label">Nro Doc</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="documento" name="documento" placeholder="Nro de Documento*">
									</div>
								</div>
								
								
								<div class="input-group col-sm-4" id="nac" name="nac" >
									<label for="ticket-nacimiento" class="col-sm-4 control-label">Fecha Nac.</label>
									<div class="input-group col-sm-8">
									<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										<input id="nacimiento" name="nacimiento" class="form-control col-sm-4 input-sm" type="text">
									</div>
								</div>	
								
						</div>
					</div>
				</div>
				<!-- FIN NUEVA EVALUACION -->
				
				<!-- DATOS CLIENTE -->
				<div class="widget">
					<div class="widget-header">
						<h3>
							<i class="fa fa-user-plus"></i> Datos Cliente
						</h3>
					</div>
					<div class="widget-content">						
						<div class="row">
						
								<div class="form-group col-sm-4">
									<label for="ticket-nombres" class="col-sm-3 control-label">Nombres</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="nombres" name="nombres" placeholder="Nombres*">
									</div>
								</div>	
								
								<div class="form-group col-sm-4">
									<label for="ticket-paterno" class="col-sm-3 control-label">Paterno</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="apellidopat" name="apellidopat" placeholder="Apellido Paterno*">
									</div>
								</div>
								
								<div class="form-group col-sm-4">
									<label for="ticket-materno" class="col-sm-3 control-label">Materno</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="apellidomat" name="apellidomat" placeholder="Apellido Materno*">
									</div>
								</div>		
								
						</div>
					</div>
				</div>
				<!-- FIN DATOS CLIENTE -->
				
				<!-- CONDICIONES DE VENTA -->
				<div class="widget">
					<div class="widget-header">
						<h3>
							<i class="fa fa-money"></i> Condiciones de Venta
						</h3>
					</div>
					<div class="widget-content">						
						<div class="row">
						
								<div class="form-group col-sm-6">
									<label class="col-md-3 control-label">Modalidad Venta</label>
									<div class="col-md-9">
										<select class="form-control input-sm" name="modalidad_venta" id="modalidad_venta">
											<option>SELECCIONE</option>
										</select>
									</div>	
								</div>	
								
								<div class="form-group col-sm-6">
									<label for="ticket-ref" class="col-sm-3 control-label">Tel Contacto</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="contacto" name="contacto" placeholder="Telefono Contacto">
									</div>
								</div>	
								
						</div>
						
						<div class="row">
						
								<div class="form-group col-sm-6">
									<label for="ticket-ref" class="col-sm-3 control-label">Observaciones</label>
									<div class="col-sm-9">
										<Textarea type="text" class="form-control" id="observaciones" name="observaciones" placeholder="Observaciones"></Textarea>
									</div>
								</div>
								
								<div class="form-group col-sm-6">
									<label for="ticket-attachment" class="col-sm-3 control-label">Documento</label>
									<div class="col-md-9">
										<input type="file" id="documentos_pdf" name="documentos_pdf">
										<p class="help-block"><em>Tipo de archivo permitido: .pdf. Tamaño maximo: 2 MB</em></p>
										<div id="adjuntos" name="adjuntos" style="display: none;">
											<label>Adjunto:</label>
											<ul class="list-unstyled uploaded-attachment">
												<li><a id="linkear_pdf" name="linkear_pdf" target="_blank" onclick="window.open(this.href, this.target, 'directories=no,titlebar=no,top=50,left=350,width=900,height=600'); return false;"><i class="fa fa-file-pdf-o"></i> <em id="document_name" name="document_name"></em></a> <a id="remove_document" name="remove_document" class="remove" style="cursor: pointer;">Eliminar</a></li>
											</ul>
										</div>
									</div>
								</div>
								
						</div>
					</div>
				</div>
				<!-- FIN CONDICIONES DE VENTA -->
				
				<!-- DATA EXPORT -->
					<div class="widget widget-table" id="myDiv" name="myDiv">
						<div class="widget-header">
							<h3><i class="fa fa-table"></i> Datos de la Linea</h3>
						</div>
				
						<div class="widget-content">
							<div class="row" id="porta" name="porta" style="display: none;">
								<div class="form-group col-sm-6">
									<label class="col-md-3 control-label">Modalidad</label>
									<div class="col-md-9">
										<select class="form-control input-sm" name="modalidad" id="modalidad">
											<option selected="selected">SELECCIONE</option>
											<option value="PREPAGO">PREPAGO</option>
											<option value="POSTPAGO">POSTPAGO</option>
										</select>
									</div>	
								</div>	
								<div class="form-group col-sm-6">
									<label class="col-md-3 control-label">Op Cedente</label>
									<div class="col-md-9">
										<select class="form-control input-sm" name="operador" id="operador">
											<option value="">SELECCIONE</option>
											<?php foreach($this->operador  as $indice =>$value):?>						
											<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
											<?php  endforeach;?>
										</select>
									</div>	
								</div>
							</div>
							
							<div class="row">
						
								<div class="form-group col-md-4">
									<label class="col-md-3 control-label">Campa&ntilde;a</label>
									<div class="col-md-9">
										<select class="form-control input-sm" name="campania" id="campania">
											<option value="">SELECCIONE</option>
										</select>
									</div>	
								</div>	
								
								<div class="form-group col-md-3">
									<label class="col-md-4 control-label">Plazo</label>
									<div class="col-md-8">
										<select class="form-control input-sm" name="acuerdo" id="acuerdo">
											<option value="">SELECCIONE</option>
										</select>
									</div>	
								</div>
								
								<div class="form-group col-md-3">
									<label class="col-md-4 control-label">Familia</label>
									<div class="col-md-8">
										<select class="form-control input-sm" name="familia" id="familia">
											<option value="">SELECCIONE</option>
											<?php foreach($this->familia  as $indice =>$value):?>						
											<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
											<?php  endforeach;?>
										</select>
									</div>	
								</div>
								
								<div class="form-group col-md-3">
									<label class="col-md-4 control-label">Plan</label>
									<div class="col-md-8">
										<select class="form-control input-sm" name="plan" id="plan">
											<option value="">SELECCIONE</option>
										</select>
									</div>	
								</div>
								
							</div>
							
							<div class="row">
								<div class="form-group col-sm-4" id="equip" name="equip">
									<label class="col-md-3 control-label">Equipo</label>
									<div class="col-md-9">
										<select class="select2" name="equipo" id="equipo">
											<option value="">SELECCIONE</option>
											<?php foreach($this->equipo  as $indice =>$value):?>						
											<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
											<?php  endforeach;?>
										</select>
									</div>	
								</div>
								
								<div class="form-group col-sm-3">
									<label class="col-md-4 control-label">Tope</label>
									<div class="col-md-8">
										<select class="js-example-basic-single js-states form-control input-sm" name="tope" id="tope">
											<option value="">SELECCIONE</option>
										</select>
									</div>	
								</div>
								
								<div class="form-group col-sm-3" style="display: none;" id="cuo" name="cuo">
									<label for="ticket-nombres" class="col-sm-4 control-label">Cuotas</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="cuotas" name="cuotas">
									</div>
								</div>	
								
								<div class="form-group col-sm-3" style="display: none;" id="lin" name="lin">
									<label for="ticket-nombres" class="col-sm-4 control-label" id="tele" name="tele">Telefono</label>
									<label for="ticket-nombres" class="col-sm-4 control-label" id="port" name="port"># Portar</label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="linea" name="linea">
									</div>
								</div>
								
							</div>
							
							<div class="row">
								<div class="form-group col-sm-12">
									<div class="col-sm-8 col-sm-offset-10">
										<button type="button" class="btn btn-info" id="btnAddRow">
											<i class="fa fa-plus-circle"></i> Agregar Plan
										</button>
									</div>
								</div>
							</div>
							
							<Textarea style="display: none;" type="text" id="arraysito" name="arraysito"></Textarea>
							
							<div style="display: none;" id="tabla_oculta" name="tabla_oculta">
								<table width="100%" id="listado" name="listado" class="table table-striped table-hover  table-bordered datatable">
									<thead>
										<tr>
											<th width="9%">Campaña</th>
											<th width="9%">Plazo</th>
											<th width="12%">Familia</th>
											<th width="7%">Plan</th>
											<th width="7%">Equipo</th>
											<th width="7%">Tope</th>
											<th width="2%">Cuotas</th>
											<th width="7%">Telefono</th>
											<th width="7%">Modalidad</th>
											<th width="7%">Op.Cedente</th>
											<th>IDCampaña</th>
											<th>IDPlazo</th>
											<th>IDFamilia</th>
											<th>IDPlan</th>
											<th>IDEquipo</th>
											<th>IDTope</th>
											<th>IDModalidad</th>
											<th>IDCedente</th>
											<th width="2%"></th>
										</tr>
									</thead>
									<tbody>
									</tbody>
								</table>	
							</div>									
						</div>
						
					</div>
				<!-- END DATA EXPORT -->
				
						<div class="row">
							<div class="form-group col-sm-6">
								<div class="col-sm-8 col-sm-offset-8" style="display: none;" id="oculto_boton" name="oculto_boton">
									<button type="button" class="btn btn-danger" id="btn_Grabar">
										<i class="fa fa-floppy-o"></i> Grabar Consulta
									</button>
								</div>
							</div>
						</div>
					
					<div class="alert alert-danger alert-dismissable" style="display: none;" id="mensajes" name="mensajes" >
					  <span id='mensaje'> </span>
					</div>
			</form>
		</div>
	</div>

	<!-- /main-content -->
</div>
<!-- /main -->
</div>
<!-- /content-wrapper -->
</div>
<!-- /row -->
</div>
<!-- /container -->
</div>
<!-- END BOTTOM: LEFT NAV AND RIGHT MAIN CONTENT -->
</div>
<!-- /wrapper -->